### ISSUE TITLE
LGPL vs. GPL licensing

### ISSUE THREAD

**Issue by rheavr** [janovetz/remez-exchange#2]
Hi Jake,
I am considering using your FIR filter library in a commercial project. From what I understand, the ability to do so relies heavily on whether the license is LGPL or GPL. It looks like the licensing file located in this repository is LGPL, but the source code comments look like standard GPL? Can you confirm the licensing on this library?

**Comment by janovetz** [comment]
The license is LGPL.  I can update the license in the source or I'll merge a PR if you submit one.

**Comment by rheavr** [comment]
Thanks for the answer, Jake! I would prefer you update the license in the source, as it feels... wrong to do it myself.

**Comment by janovetz** [comment]
No problem.  Can you point me to where it's not correct? `remez.c` lines 6-18 indicate the LGPL.

**Comment by rheavr** [comment]
I think the confusion may be in that the "L" used in "LGPL" used to stand for "Library" and currently stands for "Lesser." It was called "Library" in the Version 2 of the LGPL: https://www.gnu.org/licenses/old-licenses/lgpl-2.0.en.html. 

The lpgl.txt file you have attached is for the Version 3 ("Lesser") LGPL. I am not sure of the differences, or what is "correct" in this case. 

Edit: Maybe it's just fine the way it is, considering the source code has the following clause: 

"as published by the Free Software Foundation; either version 2 of the License, or (at your option) **any later version**."

**Comment by janovetz** [comment]
Yes, as far as I can tell, there is nothing inconsistent with the source code language and the license that it is offered under. But I'll review and see if it makes sense to update language.
